### PR TITLE
Testing comment command

### PR DESCRIPTION
**Pull request by naokikimura**

### CODE REVIEW

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by naokikimura** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article>
      @naokikimura<p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by yuruneko** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by yuruneko** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by yuruneko** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by yuruneko** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Comment by yuruneko** [comment]
<article> <p> :warning: 7 warnings could not be commented as a review comment. These warnings is probably about a change made to the base commit. If you rebase, the check may be successful. </p> <details><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>1 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>3 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>4 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>6 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote><blockquote><article><p><b>[CoffeeLint]</b> <span>Unnecessary double quotes are forbidden</span></p><details><p></p><p>7 line , 0 column in <code>app/assets/javascripts/index.js.coffee</code></p><dl><dt>Rule</dt><dd>no_unnecessary_double_quotes</dd><dt>Severity</dt><dd>error</dd></dl></details></article>
</blockquote></details> </article>

**Pull request merged**
